name: CI

on:
  push:
    branches: ['**']

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 18
  ASTRO_TELEMETRY_DISABLED: true

jobs:
  e2e-test:
    name: 'Run E2E tests (${{ matrix.os }})'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      - run: pnpm i
      - name: Test packages
        run: pnpm -r test:e2e
